exclude: >
  (?x)^(
      dist/|
      .devcontainer/devcontainer.json|
      htmlcov/|
      .tox/|
      .eggs/|
      *.egg|
      .pytest_cache/|
      .mypy_cache/|
      .coverage|
      coverage.xml|
      .DS_Store
  )
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-toml
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-typing-imports==1.14.0
        - flake8-bugbear==23.3.12
        - flake8-comprehensions==3.11.1
        - flake8-simplify==0.19.3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ['-c', 'pyproject.toml']
        exclude: ^tests/

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    -   id: python-safety-dependencies-check

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
    -   id: prettier
        types: [yaml]
        exclude: ^.*\.github/.*$

-   repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
    -   id: yamllint
        args: [--strict]

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.1
    hooks:
    -   id: shellcheck
