#!/usr/bin/env python3
"""
Constants and configuration values for NetSentinel
"""

# Connection constants
DEFAULT_TIMEOUT = 30.0
DEFAULT_RETRY_ATTEMPTS = 3
MAX_CONNECTIONS = 100
DEFAULT_PORT = 8080

# Logging constants
LOG_LEVELS = {"DEBUG": 10, "INFO": 20, "WARNING": 30, "ERROR": 40, "CRITICAL": 50}

# Event processing constants
DEFAULT_QUEUE_SIZE = 1000
DEFAULT_BATCH_SIZE = 100
DEFAULT_PROCESSING_TIMEOUT = 10.0

# Security constants
DEFAULT_HASH_ALGORITHM = "sha256"
DEFAULT_ENCRYPTION_ALGORITHM = "AES-256-GCM"
DEFAULT_KEY_SIZE = 32

# Monitoring constants
DEFAULT_METRICS_INTERVAL = 60.0
DEFAULT_HEALTH_CHECK_INTERVAL = 30.0
DEFAULT_TRACE_SAMPLE_RATE = 0.1

# File paths
DEFAULT_CONFIG_FILE = "netsentinel.conf"
DEFAULT_LOG_FILE = "netsentinel.log"
DEFAULT_DATA_DIR = "data"

# API constants
DEFAULT_API_PORT = 8080
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_TIMEOUT = 30.0

# Database constants
DEFAULT_DB_TIMEOUT = 30.0
DEFAULT_DB_POOL_SIZE = 10
DEFAULT_DB_MAX_OVERFLOW = 20

# Cache constants
DEFAULT_CACHE_TTL = 3600
DEFAULT_CACHE_MAX_SIZE = 10000

# Alert constants
DEFAULT_ALERT_TTL = 86400
DEFAULT_ESCALATION_DELAYS = [300, 900, 3600]  # 5min, 15min, 1hour

# Threat intelligence constants
DEFAULT_THREAT_FEED_UPDATE_INTERVAL = 3600  # 1 hour
DEFAULT_INDICATOR_TTL = 2592000  # 30 days
DEFAULT_CONFIDENCE_THRESHOLD = 70

# Network constants
DEFAULT_PACKET_CAPTURE_BUFFER = 65536
DEFAULT_FLOW_TIMEOUT = 300  # 5 minutes
DEFAULT_MAX_PACKET_SIZE = 65536

# Machine Learning constants
DEFAULT_MODEL_UPDATE_INTERVAL = 86400  # 24 hours
DEFAULT_TRAINING_BATCH_SIZE = 32
DEFAULT_PREDICTION_THRESHOLD = 0.5

# Error handling constants
DEFAULT_ERROR_RETRY_DELAY = 1.0
DEFAULT_ERROR_MAX_DELAY = 60.0
DEFAULT_ERROR_BACKOFF_MULTIPLIER = 2.0

# Performance constants
DEFAULT_WORKER_POOL_SIZE = 4
DEFAULT_ASYNC_POOL_SIZE = 10
DEFAULT_MEMORY_LIMIT = 1024 * 1024 * 1024  # 1GB

# Version constants
API_VERSION = "v1"
SUPPORTED_VERSIONS = ["v1"]
MIN_SUPPORTED_VERSION = "v1"

# Status codes
STATUS_OK = 200
STATUS_CREATED = 201
STATUS_BAD_REQUEST = 400
STATUS_UNAUTHORIZED = 401
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404
STATUS_INTERNAL_ERROR = 500
STATUS_SERVICE_UNAVAILABLE = 503
