global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'opencanary'
    static_configs:
      - targets: ['opencanary:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'event-processor'
    static_configs:
      - targets: ['event-processor:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s
