name: Publish to PyPI
on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/netsentinel
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: "Check out repository code"
      uses: "actions/checkout@v4"
    - name: Install build dependencies
      run: |
        pip install build
    - name: Build package
      run: python -m build
    - name: check version matches tag
      run: |
            python3 -m pip install dist/*
            # Check if netsentinel module can be imported
            python3 -c "import netsentinel; print('NetSentinel imported successfully')"
            tag_name="${{ github.event.release.tag_name }}"
            tag_name_without_v="${tag_name#v}"
            # For now, just check that the package installs correctly
            echo "Package built and installed successfully - tag: $tag_name_without_v"

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
